/**
 * Comprehensive US Cities Database
 * Includes cities, towns, and smaller places - no API needed
 */

const US_CITIES = [
  // ALABAMA
  { name: "Birmingham", state: "Alabama" },
  { name: "Montgomery", state: "Alabama" },
  { name: "Huntsville", state: "Alabama" },
  { name: "Mobile", state: "Alabama" },
  { name: "Tuscaloosa", state: "Alabama" },
  { name: "Hoover", state: "Alabama" },
  { name: "Dothan", state: "Alabama" },
  { name: "Auburn", state: "Alabama" },
  { name: "Decatur", state: "Alabama" },
  { name: "Madison", state: "Alabama" },
  { name: "Florence", state: "Alabama" },
  { name: "Gadsden", state: "Alabama" },
  { name: "Vestavia Hills", state: "Alabama" },
  { name: "Prattville", state: "Alabama" },
  { name: "Phenix City", state: "Alabama" },
  { name: "Alabaster", state: "Alabama" },
  { name: "Bessemer", state: "Alabama" },
  { name: "Enterprise", state: "Alabama" },
  { name: "Opelika", state: "Alabama" },
  { name: "Homewood", state: "Alabama" },
  { name: "Northport", state: "Alabama" },
  { name: "Anniston", state: "Alabama" },
  { name: "Prichard", state: "Alabama" },
  { name: "Athens", state: "Alabama" },

  // ALASKA
  { name: "Anchorage", state: "Alaska" },
  { name: "Fairbanks", state: "Alaska" },
  { name: "Juneau", state: "Alaska" },
  { name: "Sitka", state: "Alaska" },
  { name: "Ketchikan", state: "Alaska" },
  { name: "Wasilla", state: "Alaska" },
  { name: "Kenai", state: "Alaska" },
  { name: "Kodiak", state: "Alaska" },
  { name: "Bethel", state: "Alaska" },
  { name: "Palmer", state: "Alaska" },

  // ARIZONA
  { name: "Phoenix", state: "Arizona" },
  { name: "Tucson", state: "Arizona" },
  { name: "Mesa", state: "Arizona" },
  { name: "Chandler", state: "Arizona" },
  { name: "Scottsdale", state: "Arizona" },
  { name: "Glendale", state: "Arizona" },
  { name: "Gilbert", state: "Arizona" },
  { name: "Tempe", state: "Arizona" },
  { name: "Peoria", state: "Arizona" },
  { name: "Surprise", state: "Arizona" },
  { name: "Yuma", state: "Arizona" },
  { name: "Avondale", state: "Arizona" },
  { name: "Goodyear", state: "Arizona" },
  { name: "Flagstaff", state: "Arizona" },
  { name: "Buckeye", state: "Arizona" },
  { name: "Lake Havasu City", state: "Arizona" },
  { name: "Casa Grande", state: "Arizona" },
  { name: "Sierra Vista", state: "Arizona" },
  { name: "Maricopa", state: "Arizona" },
  { name: "Oro Valley", state: "Arizona" },
  { name: "Prescott", state: "Arizona" },
  { name: "Bullhead City", state: "Arizona" },
  { name: "Prescott Valley", state: "Arizona" },
  { name: "Marana", state: "Arizona" },
  { name: "Apache Junction", state: "Arizona" },

  // ARKANSAS
  { name: "Little Rock", state: "Arkansas" },
  { name: "Fort Smith", state: "Arkansas" },
  { name: "Fayetteville", state: "Arkansas" },
  { name: "Springdale", state: "Arkansas" },
  { name: "Jonesboro", state: "Arkansas" },
  { name: "North Little Rock", state: "Arkansas" },
  { name: "Conway", state: "Arkansas" },
  { name: "Rogers", state: "Arkansas" },
  { name: "Pine Bluff", state: "Arkansas" },
  { name: "Bentonville", state: "Arkansas" },
  { name: "Hot Springs", state: "Arkansas" },
  { name: "Benton", state: "Arkansas" },
  { name: "Texarkana", state: "Arkansas" },
  { name: "Sherwood", state: "Arkansas" },
  { name: "Jacksonville", state: "Arkansas" },
  { name: "Russellville", state: "Arkansas" },
  { name: "Bella Vista", state: "Arkansas" },
  { name: "West Memphis", state: "Arkansas" },
  { name: "Paragould", state: "Arkansas" },
  { name: "Cabot", state: "Arkansas" },

  // CALIFORNIA
  { name: "Los Angeles", state: "California" },
  { name: "San Diego", state: "California" },
  { name: "San Jose", state: "California" },
  { name: "San Francisco", state: "California" },
  { name: "Fresno", state: "California" },
  { name: "Sacramento", state: "California" },
  { name: "Long Beach", state: "California" },
  { name: "Oakland", state: "California" },
  { name: "Bakersfield", state: "California" },
  { name: "Anaheim", state: "California" },
  { name: "Santa Ana", state: "California" },
  { name: "Riverside", state: "California" },
  { name: "Stockton", state: "California" },
  { name: "Irvine", state: "California" },
  { name: "Chula Vista", state: "California" },
  { name: "Fremont", state: "California" },
  { name: "San Bernardino", state: "California" },
  { name: "Modesto", state: "California" },
  { name: "Fontana", state: "California" },
  { name: "Moreno Valley", state: "California" },
  { name: "Glendale", state: "California" },
  { name: "Huntington Beach", state: "California" },
  { name: "Santa Clarita", state: "California" },
  { name: "Garden Grove", state: "California" },
  { name: "Oceanside", state: "California" },
  { name: "Rancho Cucamonga", state: "California" },
  { name: "Santa Rosa", state: "California" },
  { name: "Ontario", state: "California" },
  { name: "Elk Grove", state: "California" },
  { name: "Corona", state: "California" },
  { name: "Lancaster", state: "California" },
  { name: "Palmdale", state: "California" },
  { name: "Salinas", state: "California" },
  { name: "Pomona", state: "California" },
  { name: "Hayward", state: "California" },
  { name: "Escondido", state: "California" },
  { name: "Sunnyvale", state: "California" },
  { name: "Torrance", state: "California" },
  { name: "Pasadena", state: "California" },
  { name: "Orange", state: "California" },
  { name: "Fullerton", state: "California" },
  { name: "Thousand Oaks", state: "California" },
  { name: "Roseville", state: "California" },
  { name: "Concord", state: "California" },
  { name: "Simi Valley", state: "California" },
  { name: "Santa Clara", state: "California" },
  { name: "Victorville", state: "California" },
  { name: "Vallejo", state: "California" },
  { name: "Berkeley", state: "California" },
  { name: "El Monte", state: "California" },
  { name: "Downey", state: "California" },
  { name: "Costa Mesa", state: "California" },
  { name: "Inglewood", state: "California" },
  { name: "Carlsbad", state: "California" },
  { name: "Fairfield", state: "California" },
  { name: "Ventura", state: "California" },
  { name: "Temecula", state: "California" },
  { name: "Antioch", state: "California" },
  { name: "Murrieta", state: "California" },
  { name: "Richmond", state: "California" },
  { name: "Norwalk", state: "California" },
  { name: "Daly City", state: "California" },
  { name: "Burbank", state: "California" },
  { name: "El Cajon", state: "California" },
  { name: "San Mateo", state: "California" },
  { name: "Rialto", state: "California" },
  { name: "Clovis", state: "California" },
  { name: "Compton", state: "California" },
  { name: "Jurupa Valley", state: "California" },
  { name: "Vista", state: "California" },
  { name: "South Gate", state: "California" },
  { name: "Mission Viejo", state: "California" },
  { name: "Vacaville", state: "California" },
  { name: "Carson", state: "California" },
  { name: "Hesperia", state: "California" },
  { name: "Santa Maria", state: "California" },
  { name: "Redding", state: "California" },
  { name: "Westminster", state: "California" },
  { name: "Santa Monica", state: "California" },
  { name: "Chico", state: "California" },
  { name: "Newport Beach", state: "California" },
  { name: "San Leandro", state: "California" },
  { name: "San Marcos", state: "California" },
  { name: "Whittier", state: "California" },
  { name: "Hawthorne", state: "California" },
  { name: "Citrus Heights", state: "California" },
  { name: "Alhambra", state: "California" },
  { name: "Tracy", state: "California" },
  { name: "Livermore", state: "California" },
  { name: "Buena Park", state: "California" },
  { name: "Menifee", state: "California" },
  { name: "Hemet", state: "California" },
  { name: "Lakewood", state: "California" },
  { name: "Merced", state: "California" },
  { name: "Chino", state: "California" },
  { name: "Indio", state: "California" },
  { name: "Redwood City", state: "California" },
  { name: "Lake Forest", state: "California" },
  { name: "Napa", state: "California" },
  { name: "Tustin", state: "California" },
  { name: "Bellflower", state: "California" },
  { name: "Mountain View", state: "California" },
  { name: "Chino Hills", state: "California" },
  { name: "Baldwin Park", state: "California" },
  { name: "Alameda", state: "California" },
  { name: "Upland", state: "California" },
  { name: "San Ramon", state: "California" },
  { name: "Folsom", state: "California" },
  { name: "Pleasanton", state: "California" },
  { name: "Lynwood", state: "California" },
  { name: "Union City", state: "California" },
  { name: "Apple Valley", state: "California" },
  { name: "Redlands", state: "California" },
  { name: "Turlock", state: "California" },
  { name: "Perris", state: "California" },
  { name: "Manteca", state: "California" },
  { name: "Milpitas", state: "California" },
  { name: "Redondo Beach", state: "California" },
  { name: "Rancho Cordova", state: "California" },
  { name: "Lake Elsinore", state: "California" },
  { name: "San Clemente", state: "California" },

  // COLORADO
  { name: "Denver", state: "Colorado" },
  { name: "Colorado Springs", state: "Colorado" },
  { name: "Aurora", state: "Colorado" },
  { name: "Fort Collins", state: "Colorado" },
  { name: "Lakewood", state: "Colorado" },
  { name: "Thornton", state: "Colorado" },
  { name: "Arvada", state: "Colorado" },
  { name: "Westminster", state: "Colorado" },
  { name: "Pueblo", state: "Colorado" },
  { name: "Centennial", state: "Colorado" },
  { name: "Boulder", state: "Colorado" },
  { name: "Greeley", state: "Colorado" },
  { name: "Longmont", state: "Colorado" },
  { name: "Loveland", state: "Colorado" },
  { name: "Grand Junction", state: "Colorado" },
  { name: "Broomfield", state: "Colorado" },
  { name: "Castle Rock", state: "Colorado" },
  { name: "Commerce City", state: "Colorado" },
  { name: "Parker", state: "Colorado" },
  { name: "Littleton", state: "Colorado" },
  { name: "Northglenn", state: "Colorado" },
  { name: "Brighton", state: "Colorado" },
  { name: "Englewood", state: "Colorado" },
  { name: "Wheat Ridge", state: "Colorado" },
  { name: "Fountain", state: "Colorado" },
  { name: "Lafayette", state: "Colorado" },
  { name: "Windsor", state: "Colorado" },
  { name: "Erie", state: "Colorado" },
  { name: "Evans", state: "Colorado" },
  { name: "Golden", state: "Colorado" },

  // CONNECTICUT
  { name: "Bridgeport", state: "Connecticut" },
  { name: "New Haven", state: "Connecticut" },
  { name: "Stamford", state: "Connecticut" },
  { name: "Hartford", state: "Connecticut" },
  { name: "Waterbury", state: "Connecticut" },
  { name: "Norwalk", state: "Connecticut" },
  { name: "Danbury", state: "Connecticut" },
  { name: "New Britain", state: "Connecticut" },
  { name: "Bristol", state: "Connecticut" },
  { name: "Meriden", state: "Connecticut" },
  { name: "Milford", state: "Connecticut" },
  { name: "West Haven", state: "Connecticut" },
  { name: "Middletown", state: "Connecticut" },
  { name: "Norwich", state: "Connecticut" },
  { name: "Shelton", state: "Connecticut" },
  { name: "Torrington", state: "Connecticut" },
  { name: "New London", state: "Connecticut" },
  { name: "Ansonia", state: "Connecticut" },
  { name: "Derby", state: "Connecticut" },
  { name: "Groton", state: "Connecticut" },

  // DELAWARE
  { name: "Wilmington", state: "Delaware" },
  { name: "Dover", state: "Delaware" },
  { name: "Newark", state: "Delaware" },
  { name: "Middletown", state: "Delaware" },
  { name: "Smyrna", state: "Delaware" },
  { name: "Milford", state: "Delaware" },
  { name: "Seaford", state: "Delaware" },
  { name: "Georgetown", state: "Delaware" },
  { name: "Elsmere", state: "Delaware" },
  { name: "New Castle", state: "Delaware" },

  // FLORIDA
  { name: "Jacksonville", state: "Florida" },
  { name: "Miami", state: "Florida" },
  { name: "Tampa", state: "Florida" },
  { name: "Orlando", state: "Florida" },
  { name: "St. Petersburg", state: "Florida" },
  { name: "Hialeah", state: "Florida" },
  { name: "Tallahassee", state: "Florida" },
  { name: "Fort Lauderdale", state: "Florida" },
  { name: "Port St. Lucie", state: "Florida" },
  { name: "Cape Coral", state: "Florida" },
  { name: "Pembroke Pines", state: "Florida" },
  { name: "Hollywood", state: "Florida" },
  { name: "Miramar", state: "Florida" },
  { name: "Gainesville", state: "Florida" },
  { name: "Coral Springs", state: "Florida" },
  { name: "Miami Gardens", state: "Florida" },
  { name: "Clearwater", state: "Florida" },
  { name: "Palm Bay", state: "Florida" },
  { name: "Pompano Beach", state: "Florida" },
  { name: "West Palm Beach", state: "Florida" },
  { name: "Lakeland", state: "Florida" },
  { name: "Davie", state: "Florida" },
  { name: "Miami Beach", state: "Florida" },
  { name: "Sunrise", state: "Florida" },
  { name: "Plantation", state: "Florida" },
  { name: "Boca Raton", state: "Florida" },
  { name: "Deltona", state: "Florida" },
  { name: "Largo", state: "Florida" },
  { name: "Deerfield Beach", state: "Florida" },
  { name: "Palm Coast", state: "Florida" },
  { name: "Melbourne", state: "Florida" },
  { name: "Boynton Beach", state: "Florida" },
  { name: "Lauderhill", state: "Florida" },
  { name: "Weston", state: "Florida" },
  { name: "Fort Myers", state: "Florida" },
  { name: "Kissimmee", state: "Florida" },
  { name: "Homestead", state: "Florida" },
  { name: "Tamarac", state: "Florida" },
  { name: "Delray Beach", state: "Florida" },
  { name: "Daytona Beach", state: "Florida" },
  { name: "North Miami", state: "Florida" },
  { name: "Wellington", state: "Florida" },
  { name: "North Port", state: "Florida" },
  { name: "Jupiter", state: "Florida" },
  { name: "Ocala", state: "Florida" },
  { name: "Port Orange", state: "Florida" },
  { name: "Margate", state: "Florida" },
  { name: "Coconut Creek", state: "Florida" },
  { name: "Sanford", state: "Florida" },
  { name: "Sarasota", state: "Florida" },
  { name: "Pensacola", state: "Florida" },
  { name: "Bradenton", state: "Florida" },
  { name: "Palm Beach Gardens", state: "Florida" },
  { name: "Pinellas Park", state: "Florida" },
  { name: "Coral Gables", state: "Florida" },
  { name: "Doral", state: "Florida" },
  { name: "Bonita Springs", state: "Florida" },
  { name: "Apopka", state: "Florida" },
  { name: "Titusville", state: "Florida" },
  { name: "North Miami Beach", state: "Florida" },
  { name: "Oakland Park", state: "Florida" },
  { name: "Fort Pierce", state: "Florida" },
  { name: "North Lauderdale", state: "Florida" },
  { name: "Cutler Bay", state: "Florida" },
  { name: "Altamonte Springs", state: "Florida" },
  { name: "St. Cloud", state: "Florida" },
  { name: "Greenacres", state: "Florida" },
  { name: "Ormond Beach", state: "Florida" },
  { name: "Ocoee", state: "Florida" },
  { name: "Hallandale Beach", state: "Florida" },
  { name: "Winter Garden", state: "Florida" },
  { name: "Aventura", state: "Florida" },
  // South Carolina cities in Florida section - MOVED TO SC
  { name: "Goose Creek", state: "South Carolina" },
  { name: "Summerville", state: "South Carolina" },
  { name: "Mount Pleasant", state: "South Carolina" },
  { name: "North Charleston", state: "South Carolina" },
  { name: "Hanahan", state: "South Carolina" },
  { name: "Ladson", state: "South Carolina" },
  { name: "Moncks Corner", state: "South Carolina" },

  // GEORGIA
  { name: "Atlanta", state: "Georgia" },
  { name: "Augusta", state: "Georgia" },
  { name: "Columbus", state: "Georgia" },
  { name: "Macon", state: "Georgia" },
  { name: "Savannah", state: "Georgia" },
  { name: "Athens", state: "Georgia" },
  { name: "Sandy Springs", state: "Georgia" },
  { name: "Roswell", state: "Georgia" },
  { name: "Johns Creek", state: "Georgia" },
  { name: "Albany", state: "Georgia" },
  { name: "Warner Robins", state: "Georgia" },
  { name: "Alpharetta", state: "Georgia" },
  { name: "Marietta", state: "Georgia" },
  { name: "Valdosta", state: "Georgia" },
  { name: "Smyrna", state: "Georgia" },
  { name: "Dunwoody", state: "Georgia" },
  { name: "Rome", state: "Georgia" },
  { name: "Peachtree City", state: "Georgia" },
  { name: "Gainesville", state: "Georgia" },
  { name: "Hinesville", state: "Georgia" },
  { name: "Dalton", state: "Georgia" },
  { name: "Newnan", state: "Georgia" },
  { name: "Milton", state: "Georgia" },
  { name: "Douglasville", state: "Georgia" },
  { name: "Kennesaw", state: "Georgia" },
  { name: "LaGrange", state: "Georgia" },
  { name: "Statesboro", state: "Georgia" },
  { name: "Lawrenceville", state: "Georgia" },
  { name: "Duluth", state: "Georgia" },
  { name: "Stockbridge", state: "Georgia" },

  // HAWAII
  { name: "Honolulu", state: "Hawaii" },
  { name: "Pearl City", state: "Hawaii" },
  { name: "Hilo", state: "Hawaii" },
  { name: "Kailua", state: "Hawaii" },
  { name: "Waipahu", state: "Hawaii" },
  { name: "Kaneohe", state: "Hawaii" },
  { name: "Mililani Town", state: "Hawaii" },
  { name: "Kahului", state: "Hawaii" },
  { name: "Ewa Gentry", state: "Hawaii" },
  { name: "Kapolei", state: "Hawaii" },

  // IDAHO
  { name: "Boise", state: "Idaho" },
  { name: "Meridian", state: "Idaho" },
  { name: "Nampa", state: "Idaho" },
  { name: "Idaho Falls", state: "Idaho" },
  { name: "Caldwell", state: "Idaho" },
  { name: "Pocatello", state: "Idaho" },
  { name: "Coeur d'Alene", state: "Idaho" },
  { name: "Twin Falls", state: "Idaho" },
  { name: "Post Falls", state: "Idaho" },
  { name: "Lewiston", state: "Idaho" },
  { name: "Rexburg", state: "Idaho" },
  { name: "Eagle", state: "Idaho" },
  { name: "Kuna", state: "Idaho" },
  { name: "Moscow", state: "Idaho" },
  { name: "Ammon", state: "Idaho" },

  // ILLINOIS
  { name: "Chicago", state: "Illinois" },
  { name: "Aurora", state: "Illinois" },
  { name: "Rockford", state: "Illinois" },
  { name: "Joliet", state: "Illinois" },
  { name: "Naperville", state: "Illinois" },
  { name: "Springfield", state: "Illinois" },
  { name: "Peoria", state: "Illinois" },
  { name: "Elgin", state: "Illinois" },
  { name: "Waukegan", state: "Illinois" },
  { name: "Champaign", state: "Illinois" },
  { name: "Bloomington", state: "Illinois" },
  { name: "Decatur", state: "Illinois" },
  { name: "Evanston", state: "Illinois" },
  { name: "Des Plaines", state: "Illinois" },
  { name: "Berwyn", state: "Illinois" },
  { name: "Wheaton", state: "Illinois" },
  { name: "Belleville", state: "Illinois" },
  { name: "Elmhurst", state: "Illinois" },
  { name: "DeKalb", state: "Illinois" },
  { name: "Moline", state: "Illinois" },
  { name: "Urbana", state: "Illinois" },
  { name: "Crystal Lake", state: "Illinois" },
  { name: "Quincy", state: "Illinois" },
  { name: "Rock Island", state: "Illinois" },
  { name: "Park Ridge", state: "Illinois" },
  { name: "Normal", state: "Illinois" },
  { name: "Highland Park", state: "Illinois" },
  { name: "Glenview", state: "Illinois" },
  { name: "Oak Lawn", state: "Illinois" },
  { name: "Bolingbrook", state: "Illinois" },

  // INDIANA
  { name: "Indianapolis", state: "Indiana" },
  { name: "Fort Wayne", state: "Indiana" },
  { name: "Evansville", state: "Indiana" },
  { name: "South Bend", state: "Indiana" },
  { name: "Carmel", state: "Indiana" },
  { name: "Bloomington", state: "Indiana" },
  { name: "Fishers", state: "Indiana" },
  { name: "Hammond", state: "Indiana" },
  { name: "Gary", state: "Indiana" },
  { name: "Muncie", state: "Indiana" },
  { name: "Lafayette", state: "Indiana" },
  { name: "Terre Haute", state: "Indiana" },
  { name: "Kokomo", state: "Indiana" },
  { name: "Anderson", state: "Indiana" },
  { name: "Noblesville", state: "Indiana" },
  { name: "Greenwood", state: "Indiana" },
  { name: "Elkhart", state: "Indiana" },
  { name: "Mishawaka", state: "Indiana" },
  { name: "Lawrence", state: "Indiana" },
  { name: "Jeffersonville", state: "Indiana" },
  { name: "Columbus", state: "Indiana" },
  { name: "Portage", state: "Indiana" },
  { name: "New Albany", state: "Indiana" },
  { name: "Richmond", state: "Indiana" },
  { name: "Westfield", state: "Indiana" },
  { name: "Valparaiso", state: "Indiana" },
  { name: "Goshen", state: "Indiana" },
  { name: "Michigan City", state: "Indiana" },
  { name: "Marion", state: "Indiana" },
  { name: "East Chicago", state: "Indiana" },

  // IOWA
  { name: "Des Moines", state: "Iowa" },
  { name: "Cedar Rapids", state: "Iowa" },
  { name: "Davenport", state: "Iowa" },
  { name: "Sioux City", state: "Iowa" },
  { name: "Iowa City", state: "Iowa" },
  { name: "Waterloo", state: "Iowa" },
  { name: "Ames", state: "Iowa" },
  { name: "West Des Moines", state: "Iowa" },
  { name: "Council Bluffs", state: "Iowa" },
  { name: "Ankeny", state: "Iowa" },
  { name: "Dubuque", state: "Iowa" },
  { name: "Urbandale", state: "Iowa" },
  { name: "Cedar Falls", state: "Iowa" },
  { name: "Marion", state: "Iowa" },
  { name: "Bettendorf", state: "Iowa" },
  { name: "Mason City", state: "Iowa" },
  { name: "Marshalltown", state: "Iowa" },
  { name: "Clinton", state: "Iowa" },
  { name: "Burlington", state: "Iowa" },
  { name: "Ottumwa", state: "Iowa" },

  // KANSAS
  { name: "Wichita", state: "Kansas" },
  { name: "Overland Park", state: "Kansas" },
  { name: "Kansas City", state: "Kansas" },
  { name: "Olathe", state: "Kansas" },
  { name: "Topeka", state: "Kansas" },
  { name: "Lawrence", state: "Kansas" },
  { name: "Shawnee", state: "Kansas" },
  { name: "Manhattan", state: "Kansas" },
  { name: "Lenexa", state: "Kansas" },
  { name: "Salina", state: "Kansas" },
  { name: "Hutchinson", state: "Kansas" },
  { name: "Leavenworth", state: "Kansas" },
  { name: "Leawood", state: "Kansas" },
  { name: "Dodge City", state: "Kansas" },
  { name: "Garden City", state: "Kansas" },
  { name: "Emporia", state: "Kansas" },
  { name: "Derby", state: "Kansas" },
  { name: "Prairie Village", state: "Kansas" },
  { name: "Junction City", state: "Kansas" },
  { name: "Hays", state: "Kansas" },

  // KENTUCKY
  { name: "Louisville", state: "Kentucky" },
  { name: "Lexington", state: "Kentucky" },
  { name: "Bowling Green", state: "Kentucky" },
  { name: "Owensboro", state: "Kentucky" },
  { name: "Covington", state: "Kentucky" },
  { name: "Richmond", state: "Kentucky" },
  { name: "Georgetown", state: "Kentucky" },
  { name: "Florence", state: "Kentucky" },
  { name: "Hopkinsville", state: "Kentucky" },
  { name: "Nicholasville", state: "Kentucky" },
  { name: "Elizabethtown", state: "Kentucky" },
  { name: "Henderson", state: "Kentucky" },
  { name: "Frankfort", state: "Kentucky" },
  { name: "Independence", state: "Kentucky" },
  { name: "Jeffersontown", state: "Kentucky" },
  { name: "Paducah", state: "Kentucky" },
  { name: "Radcliff", state: "Kentucky" },
  { name: "Ashland", state: "Kentucky" },
  { name: "Madisonville", state: "Kentucky" },
  { name: "Murray", state: "Kentucky" },

  // LOUISIANA
  { name: "New Orleans", state: "Louisiana" },
  { name: "Baton Rouge", state: "Louisiana" },
  { name: "Shreveport", state: "Louisiana" },
  { name: "Lafayette", state: "Louisiana" },
  { name: "Lake Charles", state: "Louisiana" },
  { name: "Kenner", state: "Louisiana" },
  { name: "Bossier City", state: "Louisiana" },
  { name: "Monroe", state: "Louisiana" },
  { name: "Alexandria", state: "Louisiana" },
  { name: "Houma", state: "Louisiana" },
  { name: "Marrero", state: "Louisiana" },
  { name: "New Iberia", state: "Louisiana" },
  { name: "Laplace", state: "Louisiana" },
  { name: "Slidell", state: "Louisiana" },
  { name: "Central", state: "Louisiana" },
  { name: "Ruston", state: "Louisiana" },
  { name: "Sulphur", state: "Louisiana" },
  { name: "Hammond", state: "Louisiana" },
  { name: "Zachary", state: "Louisiana" },
  { name: "Natchitoches", state: "Louisiana" },

  // MAINE
  { name: "Portland", state: "Maine" },
  { name: "Lewiston", state: "Maine" },
  { name: "Bangor", state: "Maine" },
  { name: "South Portland", state: "Maine" },
  { name: "Auburn", state: "Maine" },
  { name: "Biddeford", state: "Maine" },
  { name: "Sanford", state: "Maine" },
  { name: "Brunswick", state: "Maine" },
  { name: "Augusta", state: "Maine" },
  { name: "Saco", state: "Maine" },
  { name: "Westbrook", state: "Maine" },
  { name: "Waterville", state: "Maine" },
  { name: "Presque Isle", state: "Maine" },
  { name: "Brewer", state: "Maine" },
  { name: "Bath", state: "Maine" },

  // MARYLAND
  { name: "Baltimore", state: "Maryland" },
  { name: "Columbia", state: "Maryland" },
  { name: "Germantown", state: "Maryland" },
  { name: "Silver Spring", state: "Maryland" },
  { name: "Waldorf", state: "Maryland" },
  { name: "Frederick", state: "Maryland" },
  { name: "Ellicott City", state: "Maryland" },
  { name: "Glen Burnie", state: "Maryland" },
  { name: "Gaithersburg", state: "Maryland" },
  { name: "Rockville", state: "Maryland" },
  { name: "Bethesda", state: "Maryland" },
  { name: "Dundalk", state: "Maryland" },
  { name: "Towson", state: "Maryland" },
  { name: "Bowie", state: "Maryland" },
  { name: "Aspen Hill", state: "Maryland" },
  { name: "Wheaton", state: "Maryland" },
  { name: "Bel Air", state: "Maryland" },
  { name: "Annapolis", state: "Maryland" },
  { name: "Hagerstown", state: "Maryland" },
  { name: "Severn", state: "Maryland" },
  { name: "College Park", state: "Maryland" },
  { name: "Salisbury", state: "Maryland" },
  { name: "Laurel", state: "Maryland" },
  { name: "Catonsville", state: "Maryland" },
  { name: "Odenton", state: "Maryland" },

  // MASSACHUSETTS
  { name: "Boston", state: "Massachusetts" },
  { name: "Worcester", state: "Massachusetts" },
  { name: "Springfield", state: "Massachusetts" },
  { name: "Lowell", state: "Massachusetts" },
  { name: "Cambridge", state: "Massachusetts" },
  { name: "New Bedford", state: "Massachusetts" },
  { name: "Brockton", state: "Massachusetts" },
  { name: "Quincy", state: "Massachusetts" },
  { name: "Lynn", state: "Massachusetts" },
  { name: "Fall River", state: "Massachusetts" },
  { name: "Newton", state: "Massachusetts" },
  { name: "Lawrence", state: "Massachusetts" },
  { name: "Somerville", state: "Massachusetts" },
  { name: "Framingham", state: "Massachusetts" },
  { name: "Haverhill", state: "Massachusetts" },
  { name: "Waltham", state: "Massachusetts" },
  { name: "Malden", state: "Massachusetts" },
  { name: "Brookline", state: "Massachusetts" },
  { name: "Plymouth", state: "Massachusetts" },
  { name: "Medford", state: "Massachusetts" },
  { name: "Taunton", state: "Massachusetts" },
  { name: "Chicopee", state: "Massachusetts" },
  { name: "Weymouth", state: "Massachusetts" },
  { name: "Revere", state: "Massachusetts" },
  { name: "Peabody", state: "Massachusetts" },
  { name: "Methuen", state: "Massachusetts" },
  { name: "Barnstable", state: "Massachusetts" },
  { name: "Pittsfield", state: "Massachusetts" },
  { name: "Attleboro", state: "Massachusetts" },
  { name: "Arlington", state: "Massachusetts" },

  // MICHIGAN
  { name: "Detroit", state: "Michigan" },
  { name: "Grand Rapids", state: "Michigan" },
  { name: "Warren", state: "Michigan" },
  { name: "Sterling Heights", state: "Michigan" },
  { name: "Ann Arbor", state: "Michigan" },
  { name: "Lansing", state: "Michigan" },
  { name: "Flint", state: "Michigan" },
  { name: "Dearborn", state: "Michigan" },
  { name: "Livonia", state: "Michigan" },
  { name: "Troy", state: "Michigan" },
  { name: "Westland", state: "Michigan" },
  { name: "Farmington Hills", state: "Michigan" },
  { name: "Kalamazoo", state: "Michigan" },
  { name: "Wyoming", state: "Michigan" },
  { name: "Southfield", state: "Michigan" },
  { name: "Rochester Hills", state: "Michigan" },
  { name: "Taylor", state: "Michigan" },
  { name: "Pontiac", state: "Michigan" },
  { name: "St. Clair Shores", state: "Michigan" },
  { name: "Royal Oak", state: "Michigan" },
  { name: "Novi", state: "Michigan" },
  { name: "Dearborn Heights", state: "Michigan" },
  { name: "Battle Creek", state: "Michigan" },
  { name: "Saginaw", state: "Michigan" },
  { name: "Kentwood", state: "Michigan" },
  { name: "East Lansing", state: "Michigan" },
  { name: "Roseville", state: "Michigan" },
  { name: "Portage", state: "Michigan" },
  { name: "Midland", state: "Michigan" },
  { name: "Lincoln Park", state: "Michigan" },

  // MINNESOTA
  { name: "Minneapolis", state: "Minnesota" },
  { name: "St. Paul", state: "Minnesota" },
  { name: "Rochester", state: "Minnesota" },
  { name: "Duluth", state: "Minnesota" },
  { name: "Bloomington", state: "Minnesota" },
  { name: "Brooklyn Park", state: "Minnesota" },
  { name: "Plymouth", state: "Minnesota" },
  { name: "St. Cloud", state: "Minnesota" },
  { name: "Eagan", state: "Minnesota" },
  { name: "Woodbury", state: "Minnesota" },
  { name: "Maple Grove", state: "Minnesota" },
  { name: "Eden Prairie", state: "Minnesota" },
  { name: "Coon Rapids", state: "Minnesota" },
  { name: "Burnsville", state: "Minnesota" },
  { name: "Blaine", state: "Minnesota" },
  { name: "Lakeville", state: "Minnesota" },
  { name: "Minnetonka", state: "Minnesota" },
  { name: "Apple Valley", state: "Minnesota" },
  { name: "Edina", state: "Minnesota" },
  { name: "St. Louis Park", state: "Minnesota" },
  { name: "Mankato", state: "Minnesota" },
  { name: "Maplewood", state: "Minnesota" },
  { name: "Moorhead", state: "Minnesota" },
  { name: "Shakopee", state: "Minnesota" },
  { name: "Richfield", state: "Minnesota" },

  // MISSISSIPPI
  { name: "Jackson", state: "Mississippi" },
  { name: "Gulfport", state: "Mississippi" },
  { name: "Southaven", state: "Mississippi" },
  { name: "Hattiesburg", state: "Mississippi" },
  { name: "Biloxi", state: "Mississippi" },
  { name: "Meridian", state: "Mississippi" },
  { name: "Tupelo", state: "Mississippi" },
  { name: "Olive Branch", state: "Mississippi" },
  { name: "Greenville", state: "Mississippi" },
  { name: "Horn Lake", state: "Mississippi" },
  { name: "Clinton", state: "Mississippi" },
  { name: "Pearl", state: "Mississippi" },
  { name: "Madison", state: "Mississippi" },
  { name: "Starkville", state: "Mississippi" },
  { name: "Ridgeland", state: "Mississippi" },
  { name: "Columbus", state: "Mississippi" },
  { name: "Vicksburg", state: "Mississippi" },
  { name: "Pascagoula", state: "Mississippi" },
  { name: "Brandon", state: "Mississippi" },
  { name: "Oxford", state: "Mississippi" },

  // MISSOURI
  { name: "Kansas City", state: "Missouri" },
  { name: "St. Louis", state: "Missouri" },
  { name: "Springfield", state: "Missouri" },
  { name: "Columbia", state: "Missouri" },
  { name: "Independence", state: "Missouri" },
  { name: "Lee's Summit", state: "Missouri" },
  { name: "O'Fallon", state: "Missouri" },
  { name: "St. Joseph", state: "Missouri" },
  { name: "St. Charles", state: "Missouri" },
  { name: "St. Peters", state: "Missouri" },
  { name: "Blue Springs", state: "Missouri" },
  { name: "Florissant", state: "Missouri" },
  { name: "Joplin", state: "Missouri" },
  { name: "Chesterfield", state: "Missouri" },
  { name: "Jefferson City", state: "Missouri" },
  { name: "Cape Girardeau", state: "Missouri" },
  { name: "Wildwood", state: "Missouri" },
  { name: "University City", state: "Missouri" },
  { name: "Ballwin", state: "Missouri" },
  { name: "Raytown", state: "Missouri" },
  { name: "Liberty", state: "Missouri" },
  { name: "Wentzville", state: "Missouri" },
  { name: "Mehlville", state: "Missouri" },
  { name: "Kirkwood", state: "Missouri" },
  { name: "Maryland Heights", state: "Missouri" },

  // MONTANA
  { name: "Billings", state: "Montana" },
  { name: "Missoula", state: "Montana" },
  { name: "Great Falls", state: "Montana" },
  { name: "Bozeman", state: "Montana" },
  { name: "Butte", state: "Montana" },
  { name: "Helena", state: "Montana" },
  { name: "Kalispell", state: "Montana" },
  { name: "Havre", state: "Montana" },
  { name: "Anaconda", state: "Montana" },
  { name: "Miles City", state: "Montana" },

  // NEBRASKA
  { name: "Omaha", state: "Nebraska" },
  { name: "Lincoln", state: "Nebraska" },
  { name: "Bellevue", state: "Nebraska" },
  { name: "Grand Island", state: "Nebraska" },
  { name: "Kearney", state: "Nebraska" },
  { name: "Fremont", state: "Nebraska" },
  { name: "Hastings", state: "Nebraska" },
  { name: "Norfolk", state: "Nebraska" },
  { name: "North Platte", state: "Nebraska" },
  { name: "Columbus", state: "Nebraska" },
  { name: "Papillion", state: "Nebraska" },
  { name: "La Vista", state: "Nebraska" },
  { name: "Scottsbluff", state: "Nebraska" },
  { name: "South Sioux City", state: "Nebraska" },
  { name: "Beatrice", state: "Nebraska" },

  // NEVADA
  { name: "Las Vegas", state: "Nevada" },
  { name: "Henderson", state: "Nevada" },
  { name: "Reno", state: "Nevada" },
  { name: "North Las Vegas", state: "Nevada" },
  { name: "Sparks", state: "Nevada" },
  { name: "Carson City", state: "Nevada" },
  { name: "Fernley", state: "Nevada" },
  { name: "Elko", state: "Nevada" },
  { name: "Mesquite", state: "Nevada" },
  { name: "Boulder City", state: "Nevada" },
  { name: "Fallon", state: "Nevada" },
  { name: "Winnemucca", state: "Nevada" },
  { name: "West Wendover", state: "Nevada" },
  { name: "Ely", state: "Nevada" },
  { name: "Yerington", state: "Nevada" },

  // NEW HAMPSHIRE
  { name: "Manchester", state: "New Hampshire" },
  { name: "Nashua", state: "New Hampshire" },
  { name: "Concord", state: "New Hampshire" },
  { name: "Derry", state: "New Hampshire" },
  { name: "Dover", state: "New Hampshire" },
  { name: "Rochester", state: "New Hampshire" },
  { name: "Salem", state: "New Hampshire" },
  { name: "Merrimack", state: "New Hampshire" },
  { name: "Hudson", state: "New Hampshire" },
  { name: "Londonderry", state: "New Hampshire" },
  { name: "Keene", state: "New Hampshire" },
  { name: "Bedford", state: "New Hampshire" },
  { name: "Portsmouth", state: "New Hampshire" },
  { name: "Goffstown", state: "New Hampshire" },
  { name: "Laconia", state: "New Hampshire" },

  // NEW JERSEY
  { name: "Newark", state: "New Jersey" },
  { name: "Jersey City", state: "New Jersey" },
  { name: "Paterson", state: "New Jersey" },
  { name: "Elizabeth", state: "New Jersey" },
  { name: "Edison", state: "New Jersey" },
  { name: "Woodbridge", state: "New Jersey" },
  { name: "Lakewood", state: "New Jersey" },
  { name: "Toms River", state: "New Jersey" },
  { name: "Hamilton", state: "New Jersey" },
  { name: "Trenton", state: "New Jersey" },
  { name: "Clifton", state: "New Jersey" },
  { name: "Camden", state: "New Jersey" },
  { name: "Brick", state: "New Jersey" },
  { name: "Cherry Hill", state: "New Jersey" },
  { name: "Passaic", state: "New Jersey" },
  { name: "Middletown", state: "New Jersey" },
  { name: "Union City", state: "New Jersey" },
  { name: "Old Bridge", state: "New Jersey" },
  { name: "Gloucester", state: "New Jersey" },
  { name: "East Orange", state: "New Jersey" },
  { name: "Bayonne", state: "New Jersey" },
  { name: "Franklin", state: "New Jersey" },
  { name: "North Bergen", state: "New Jersey" },
  { name: "Vineland", state: "New Jersey" },
  { name: "Union", state: "New Jersey" },
  { name: "Piscataway", state: "New Jersey" },
  { name: "New Brunswick", state: "New Jersey" },
  { name: "Jackson", state: "New Jersey" },
  { name: "Wayne", state: "New Jersey" },
  { name: "Irvington", state: "New Jersey" },

  // NEW MEXICO
  { name: "Albuquerque", state: "New Mexico" },
  { name: "Las Cruces", state: "New Mexico" },
  { name: "Rio Rancho", state: "New Mexico" },
  { name: "Santa Fe", state: "New Mexico" },
  { name: "Roswell", state: "New Mexico" },
  { name: "Farmington", state: "New Mexico" },
  { name: "Clovis", state: "New Mexico" },
  { name: "Hobbs", state: "New Mexico" },
  { name: "Alamogordo", state: "New Mexico" },
  { name: "Carlsbad", state: "New Mexico" },
  { name: "Gallup", state: "New Mexico" },
  { name: "Deming", state: "New Mexico" },
  { name: "Los Lunas", state: "New Mexico" },
  { name: "Chaparral", state: "New Mexico" },
  { name: "Sunland Park", state: "New Mexico" },

  // NEW YORK
  { name: "New York City", state: "New York" },
  { name: "Buffalo", state: "New York" },
  { name: "Rochester", state: "New York" },
  { name: "Yonkers", state: "New York" },
  { name: "Syracuse", state: "New York" },
  { name: "Albany", state: "New York" },
  { name: "New Rochelle", state: "New York" },
  { name: "Mount Vernon", state: "New York" },
  { name: "Schenectady", state: "New York" },
  { name: "Utica", state: "New York" },
  { name: "White Plains", state: "New York" },
  { name: "Hempstead", state: "New York" },
  { name: "Troy", state: "New York" },
  { name: "Niagara Falls", state: "New York" },
  { name: "Binghamton", state: "New York" },
  { name: "Freeport", state: "New York" },
  { name: "Valley Stream", state: "New York" },
  { name: "Long Beach", state: "New York" },
  { name: "Spring Valley", state: "New York" },
  { name: "Rome", state: "New York" },
  { name: "Ithaca", state: "New York" },
  { name: "Poughkeepsie", state: "New York" },
  { name: "North Tonawanda", state: "New York" },
  { name: "Jamestown", state: "New York" },
  { name: "Elmira", state: "New York" },
  { name: "Newburgh", state: "New York" },
  { name: "Nanuet", state: "New York" },
  { name: "West Babylon", state: "New York" },
  { name: "Middletown", state: "New York" },
  { name: "Auburn", state: "New York" },

  // NORTH CAROLINA
  { name: "Charlotte", state: "North Carolina" },
  { name: "Raleigh", state: "North Carolina" },
  { name: "Greensboro", state: "North Carolina" },
  { name: "Durham", state: "North Carolina" },
  { name: "Winston-Salem", state: "North Carolina" },
  { name: "Fayetteville", state: "North Carolina" },
  { name: "Cary", state: "North Carolina" },
  { name: "Wilmington", state: "North Carolina" },
  { name: "High Point", state: "North Carolina" },
  { name: "Greenville", state: "North Carolina" },
  { name: "Asheville", state: "North Carolina" },
  { name: "Concord", state: "North Carolina" },
  { name: "Gastonia", state: "North Carolina" },
  { name: "Jacksonville", state: "North Carolina" },
  { name: "Chapel Hill", state: "North Carolina" },
  { name: "Rocky Mount", state: "North Carolina" },
  { name: "Burlington", state: "North Carolina" },
  { name: "Huntersville", state: "North Carolina" },
  { name: "Kannapolis", state: "North Carolina" },
  { name: "Apex", state: "North Carolina" },
  { name: "Hickory", state: "North Carolina" },
  { name: "Goldsboro", state: "North Carolina" },
  { name: "Indian Trail", state: "North Carolina" },
  { name: "Mooresville", state: "North Carolina" },
  { name: "Wake Forest", state: "North Carolina" },
  { name: "Monroe", state: "North Carolina" },
  { name: "Salisbury", state: "North Carolina" },
  { name: "Matthews", state: "North Carolina" },
  { name: "Sanford", state: "North Carolina" },
  { name: "New Bern", state: "North Carolina" },

  // NORTH DAKOTA
  { name: "Fargo", state: "North Dakota" },
  { name: "Bismarck", state: "North Dakota" },
  { name: "Grand Forks", state: "North Dakota" },
  { name: "Minot", state: "North Dakota" },
  { name: "West Fargo", state: "North Dakota" },
  { name: "Williston", state: "North Dakota" },
  { name: "Dickinson", state: "North Dakota" },
  { name: "Mandan", state: "North Dakota" },
  { name: "Jamestown", state: "North Dakota" },
  { name: "Wahpeton", state: "North Dakota" },

  // OHIO
  { name: "Columbus", state: "Ohio" },
  { name: "Cleveland", state: "Ohio" },
  { name: "Cincinnati", state: "Ohio" },
  { name: "Toledo", state: "Ohio" },
  { name: "Akron", state: "Ohio" },
  { name: "Dayton", state: "Ohio" },
  { name: "Parma", state: "Ohio" },
  { name: "Canton", state: "Ohio" },
  { name: "Youngstown", state: "Ohio" },
  { name: "Lorain", state: "Ohio" },
  { name: "Hamilton", state: "Ohio" },
  { name: "Springfield", state: "Ohio" },
  { name: "Kettering", state: "Ohio" },
  { name: "Elyria", state: "Ohio" },
  { name: "Lakewood", state: "Ohio" },
  { name: "Cuyahoga Falls", state: "Ohio" },
  { name: "Middletown", state: "Ohio" },
  { name: "Euclid", state: "Ohio" },
  { name: "Newark", state: "Ohio" },
  { name: "Mansfield", state: "Ohio" },
  { name: "Mentor", state: "Ohio" },
  { name: "Beavercreek", state: "Ohio" },
  { name: "Cleveland Heights", state: "Ohio" },
  { name: "Strongsville", state: "Ohio" },
  { name: "Dublin", state: "Ohio" },
  { name: "Fairfield", state: "Ohio" },
  { name: "Findlay", state: "Ohio" },
  { name: "Warren", state: "Ohio" },
  { name: "Lancaster", state: "Ohio" },
  { name: "Lima", state: "Ohio" },

  // OKLAHOMA
  { name: "Oklahoma City", state: "Oklahoma" },
  { name: "Tulsa", state: "Oklahoma" },
  { name: "Norman", state: "Oklahoma" },
  { name: "Broken Arrow", state: "Oklahoma" },
  { name: "Lawton", state: "Oklahoma" },
  { name: "Edmond", state: "Oklahoma" },
  { name: "Moore", state: "Oklahoma" },
  { name: "Midwest City", state: "Oklahoma" },
  { name: "Enid", state: "Oklahoma" },
  { name: "Stillwater", state: "Oklahoma" },
  { name: "Muskogee", state: "Oklahoma" },
  { name: "Bartlesville", state: "Oklahoma" },
  { name: "Owasso", state: "Oklahoma" },
  { name: "Shawnee", state: "Oklahoma" },
  { name: "Ponca City", state: "Oklahoma" },
  { name: "Ardmore", state: "Oklahoma" },
  { name: "Duncan", state: "Oklahoma" },
  { name: "Del City", state: "Oklahoma" },
  { name: "Bixby", state: "Oklahoma" },
  { name: "Yukon", state: "Oklahoma" },

  // OREGON
  { name: "Portland", state: "Oregon" },
  { name: "Salem", state: "Oregon" },
  { name: "Eugene", state: "Oregon" },
  { name: "Gresham", state: "Oregon" },
  { name: "Hillsboro", state: "Oregon" },
  { name: "Beaverton", state: "Oregon" },
  { name: "Bend", state: "Oregon" },
  { name: "Medford", state: "Oregon" },
  { name: "Springfield", state: "Oregon" },
  { name: "Corvallis", state: "Oregon" },
  { name: "Albany", state: "Oregon" },
  { name: "Tigard", state: "Oregon" },
  { name: "Lake Oswego", state: "Oregon" },
  { name: "Keizer", state: "Oregon" },
  { name: "Grants Pass", state: "Oregon" },
  { name: "Oregon City", state: "Oregon" },
  { name: "McMinnville", state: "Oregon" },
  { name: "Redmond", state: "Oregon" },
  { name: "Tualatin", state: "Oregon" },
  { name: "West Linn", state: "Oregon" },

  // PENNSYLVANIA
  { name: "Philadelphia", state: "Pennsylvania" },
  { name: "Pittsburgh", state: "Pennsylvania" },
  { name: "Allentown", state: "Pennsylvania" },
  { name: "Reading", state: "Pennsylvania" },
  { name: "Scranton", state: "Pennsylvania" },
  { name: "Bethlehem", state: "Pennsylvania" },
  { name: "Lancaster", state: "Pennsylvania" },
  { name: "Harrisburg", state: "Pennsylvania" },
  { name: "Altoona", state: "Pennsylvania" },
  { name: "Erie", state: "Pennsylvania" },
  { name: "York", state: "Pennsylvania" },
  { name: "Wilkes-Barre", state: "Pennsylvania" },
  { name: "Chester", state: "Pennsylvania" },
  { name: "Williamsport", state: "Pennsylvania" },
  { name: "Easton", state: "Pennsylvania" },
  { name: "Lebanon", state: "Pennsylvania" },
  { name: "Hazleton", state: "Pennsylvania" },
  { name: "New Castle", state: "Pennsylvania" },
  { name: "Johnstown", state: "Pennsylvania" },
  { name: "McKeesport", state: "Pennsylvania" },
  { name: "Hermitage", state: "Pennsylvania" },
  { name: "Greensburg", state: "Pennsylvania" },
  { name: "Pottsville", state: "Pennsylvania" },
  { name: "Sharon", state: "Pennsylvania" },
  { name: "Butler", state: "Pennsylvania" },

  // RHODE ISLAND
  { name: "Providence", state: "Rhode Island" },
  { name: "Warwick", state: "Rhode Island" },
  { name: "Cranston", state: "Rhode Island" },
  { name: "Pawtucket", state: "Rhode Island" },
  { name: "East Providence", state: "Rhode Island" },
  { name: "Woonsocket", state: "Rhode Island" },
  { name: "Coventry", state: "Rhode Island" },
  { name: "Cumberland", state: "Rhode Island" },
  { name: "North Providence", state: "Rhode Island" },
  { name: "South Kingstown", state: "Rhode Island" },
  { name: "West Warwick", state: "Rhode Island" },
  { name: "Johnston", state: "Rhode Island" },
  { name: "North Kingstown", state: "Rhode Island" },
  { name: "Newport", state: "Rhode Island" },
  { name: "Bristol", state: "Rhode Island" },

  // SOUTH CAROLINA
  { name: "Charleston", state: "South Carolina" },
  { name: "Columbia", state: "South Carolina" },
  { name: "North Charleston", state: "South Carolina" },
  { name: "Mount Pleasant", state: "South Carolina" },
  { name: "Rock Hill", state: "South Carolina" },
  { name: "Greenville", state: "South Carolina" },
  { name: "Summerville", state: "South Carolina" },
  { name: "Sumter", state: "South Carolina" },
  { name: "Goose Creek", state: "South Carolina" },
  { name: "Hilton Head Island", state: "South Carolina" },
  { name: "Florence", state: "South Carolina" },
  { name: "Spartanburg", state: "South Carolina" },
  { name: "Myrtle Beach", state: "South Carolina" },
  { name: "Aiken", state: "South Carolina" },
  { name: "Anderson", state: "South Carolina" },
  { name: "Mauldin", state: "South Carolina" },
  { name: "Greenwood", state: "South Carolina" },
  { name: "North Augusta", state: "South Carolina" },
  { name: "Easley", state: "South Carolina" },
  { name: "Simpsonville", state: "South Carolina" },
  { name: "Hanahan", state: "South Carolina" },
  { name: "Lexington", state: "South Carolina" },
  { name: "Conway", state: "South Carolina" },
  { name: "West Columbia", state: "South Carolina" },
  { name: "North Myrtle Beach", state: "South Carolina" },
  { name: "Clemson", state: "South Carolina" },
  { name: "Orangeburg", state: "South Carolina" },
  { name: "Cayce", state: "South Carolina" },
  { name: "Bluffton", state: "South Carolina" },
  { name: "Beaufort", state: "South Carolina" },
  { name: "Ladson", state: "South Carolina" },
  { name: "Moncks Corner", state: "South Carolina" },
  { name: "Irmo", state: "South Carolina" },
  { name: "Fort Mill", state: "South Carolina" },
  { name: "Tega Cay", state: "South Carolina" },

  // SOUTH DAKOTA
  { name: "Sioux Falls", state: "South Dakota" },
  { name: "Rapid City", state: "South Dakota" },
  { name: "Aberdeen", state: "South Dakota" },
  { name: "Brookings", state: "South Dakota" },
  { name: "Watertown", state: "South Dakota" },
  { name: "Mitchell", state: "South Dakota" },
  { name: "Yankton", state: "South Dakota" },
  { name: "Pierre", state: "South Dakota" },
  { name: "Huron", state: "South Dakota" },
  { name: "Spearfish", state: "South Dakota" },

  // TENNESSEE
  { name: "Nashville", state: "Tennessee" },
  { name: "Memphis", state: "Tennessee" },
  { name: "Knoxville", state: "Tennessee" },
  { name: "Chattanooga", state: "Tennessee" },
  { name: "Clarksville", state: "Tennessee" },
  { name: "Murfreesboro", state: "Tennessee" },
  { name: "Franklin", state: "Tennessee" },
  { name: "Jackson", state: "Tennessee" },
  { name: "Johnson City", state: "Tennessee" },
  { name: "Bartlett", state: "Tennessee" },
  { name: "Hendersonville", state: "Tennessee" },
  { name: "Kingsport", state: "Tennessee" },
  { name: "Collierville", state: "Tennessee" },
  { name: "Cleveland", state: "Tennessee" },
  { name: "Smyrna", state: "Tennessee" },
  { name: "Germantown", state: "Tennessee" },
  { name: "Brentwood", state: "Tennessee" },
  { name: "Columbia", state: "Tennessee" },
  { name: "Spring Hill", state: "Tennessee" },
  { name: "La Vergne", state: "Tennessee" },
  { name: "Gallatin", state: "Tennessee" },
  { name: "Cookeville", state: "Tennessee" },
  { name: "Lebanon", state: "Tennessee" },
  { name: "Mount Juliet", state: "Tennessee" },
  { name: "Morristown", state: "Tennessee" },

  // TEXAS
  { name: "Houston", state: "Texas" },
  { name: "San Antonio", state: "Texas" },
  { name: "Dallas", state: "Texas" },
  { name: "Austin", state: "Texas" },
  { name: "Fort Worth", state: "Texas" },
  { name: "El Paso", state: "Texas" },
  { name: "Arlington", state: "Texas" },
  { name: "Corpus Christi", state: "Texas" },
  { name: "Plano", state: "Texas" },
  { name: "Laredo", state: "Texas" },
  { name: "Lubbock", state: "Texas" },
  { name: "Garland", state: "Texas" },
  { name: "Irving", state: "Texas" },
  { name: "Amarillo", state: "Texas" },
  { name: "Grand Prairie", state: "Texas" },
  { name: "Brownsville", state: "Texas" },
  { name: "McKinney", state: "Texas" },
  { name: "Frisco", state: "Texas" },
  { name: "Pasadena", state: "Texas" },
  { name: "Mesquite", state: "Texas" },
  { name: "Killeen", state: "Texas" },
  { name: "McAllen", state: "Texas" },
  { name: "Waco", state: "Texas" },
  { name: "Denton", state: "Texas" },
  { name: "Carrollton", state: "Texas" },
  { name: "Midland", state: "Texas" },
  { name: "Abilene", state: "Texas" },
  { name: "Beaumont", state: "Texas" },
  { name: "Round Rock", state: "Texas" },
  { name: "Odessa", state: "Texas" },
  { name: "Richardson", state: "Texas" },
  { name: "Pearland", state: "Texas" },
  { name: "College Station", state: "Texas" },
  { name: "League City", state: "Texas" },
  { name: "Lewisville", state: "Texas" },
  { name: "Tyler", state: "Texas" },
  { name: "San Angelo", state: "Texas" },
  { name: "Wichita Falls", state: "Texas" },
  { name: "Allen", state: "Texas" },
  { name: "Edinburg", state: "Texas" },
  { name: "Sugar Land", state: "Texas" },
  { name: "Mission", state: "Texas" },
  { name: "Longview", state: "Texas" },
  { name: "Bryan", state: "Texas" },
  { name: "Pharr", state: "Texas" },
  { name: "Baytown", state: "Texas" },
  { name: "Missouri City", state: "Texas" },
  { name: "Temple", state: "Texas" },
  { name: "Flower Mound", state: "Texas" },
  { name: "New Braunfels", state: "Texas" },
  { name: "North Richland Hills", state: "Texas" },
  { name: "Conroe", state: "Texas" },
  { name: "Victoria", state: "Texas" },
  { name: "Cedar Park", state: "Texas" },
  { name: "Harlingen", state: "Texas" },
  { name: "Atascocita", state: "Texas" },
  { name: "Mansfield", state: "Texas" },
  { name: "Georgetown", state: "Texas" },
  { name: "San Marcos", state: "Texas" },
  { name: "Rowlett", state: "Texas" },
  { name: "Pflugerville", state: "Texas" },
  { name: "Port Arthur", state: "Texas" },
  { name: "Euless", state: "Texas" },
  { name: "DeSoto", state: "Texas" },
  { name: "Grapevine", state: "Texas" },
  { name: "Galveston", state: "Texas" },
  { name: "Bedford", state: "Texas" },
  { name: "Cedar Hill", state: "Texas" },
  { name: "Texas City", state: "Texas" },
  { name: "Wylie", state: "Texas" },
  { name: "Haltom City", state: "Texas" },
  { name: "Keller", state: "Texas" },
  { name: "Rockwall", state: "Texas" },
  { name: "Burleson", state: "Texas" },
  { name: "Coppell", state: "Texas" },
  { name: "Huntsville", state: "Texas" },
  { name: "Duncanville", state: "Texas" },
  { name: "Sherman", state: "Texas" },
  { name: "The Colony", state: "Texas" },
  { name: "Hurst", state: "Texas" },
  { name: "Lancaster", state: "Texas" },
  { name: "Texarkana", state: "Texas" },
  { name: "Friendswood", state: "Texas" },
  { name: "Weslaco", state: "Texas" },

  // UTAH
  { name: "Salt Lake City", state: "Utah" },
  { name: "West Valley City", state: "Utah" },
  { name: "Provo", state: "Utah" },
  { name: "West Jordan", state: "Utah" },
  { name: "Orem", state: "Utah" },
  { name: "Sandy", state: "Utah" },
  { name: "Ogden", state: "Utah" },
  { name: "St. George", state: "Utah" },
  { name: "Layton", state: "Utah" },
  { name: "Taylorsville", state: "Utah" },
  { name: "South Jordan", state: "Utah" },
  { name: "Lehi", state: "Utah" },
  { name: "Logan", state: "Utah" },
  { name: "Murray", state: "Utah" },
  { name: "Draper", state: "Utah" },
  { name: "Bountiful", state: "Utah" },
  { name: "Riverton", state: "Utah" },
  { name: "Herriman", state: "Utah" },
  { name: "Spanish Fork", state: "Utah" },
  { name: "Roy", state: "Utah" },
  { name: "Pleasant Grove", state: "Utah" },
  { name: "Kearns", state: "Utah" },
  { name: "Tooele", state: "Utah" },
  { name: "Cottonwood Heights", state: "Utah" },
  { name: "Midvale", state: "Utah" },

  // VERMONT
  { name: "Burlington", state: "Vermont" },
  { name: "South Burlington", state: "Vermont" },
  { name: "Rutland", state: "Vermont" },
  { name: "Barre", state: "Vermont" },
  { name: "Montpelier", state: "Vermont" },
  { name: "Winooski", state: "Vermont" },
  { name: "St. Albans", state: "Vermont" },
  { name: "Newport", state: "Vermont" },
  { name: "Vergennes", state: "Vermont" },
  { name: "Brattleboro", state: "Vermont" },

  // VIRGINIA
  { name: "Virginia Beach", state: "Virginia" },
  { name: "Norfolk", state: "Virginia" },
  { name: "Chesapeake", state: "Virginia" },
  { name: "Richmond", state: "Virginia" },
  { name: "Newport News", state: "Virginia" },
  { name: "Alexandria", state: "Virginia" },
  { name: "Hampton", state: "Virginia" },
  { name: "Roanoke", state: "Virginia" },
  { name: "Portsmouth", state: "Virginia" },
  { name: "Suffolk", state: "Virginia" },
  { name: "Lynchburg", state: "Virginia" },
  { name: "Harrisonburg", state: "Virginia" },
  { name: "Leesburg", state: "Virginia" },
  { name: "Charlottesville", state: "Virginia" },
  { name: "Danville", state: "Virginia" },
  { name: "Blacksburg", state: "Virginia" },
  { name: "Manassas", state: "Virginia" },
  { name: "Petersburg", state: "Virginia" },
  { name: "Fredericksburg", state: "Virginia" },
  { name: "Winchester", state: "Virginia" },
  { name: "Salem", state: "Virginia" },
  { name: "Herndon", state: "Virginia" },
  { name: "Staunton", state: "Virginia" },
  { name: "Fairfax", state: "Virginia" },
  { name: "Hopewell", state: "Virginia" },
  { name: "Christiansburg", state: "Virginia" },
  { name: "Waynesboro", state: "Virginia" },
  { name: "Colonial Heights", state: "Virginia" },
  { name: "Radford", state: "Virginia" },
  { name: "Bristol", state: "Virginia" },

  // WASHINGTON
  { name: "Seattle", state: "Washington" },
  { name: "Spokane", state: "Washington" },
  { name: "Tacoma", state: "Washington" },
  { name: "Vancouver", state: "Washington" },
  { name: "Bellevue", state: "Washington" },
  { name: "Kent", state: "Washington" },
  { name: "Everett", state: "Washington" },
  { name: "Renton", state: "Washington" },
  { name: "Spokane Valley", state: "Washington" },
  { name: "Federal Way", state: "Washington" },
  { name: "Yakima", state: "Washington" },
  { name: "Kirkland", state: "Washington" },
  { name: "Bellingham", state: "Washington" },
  { name: "Kennewick", state: "Washington" },
  { name: "Auburn", state: "Washington" },
  { name: "Pasco", state: "Washington" },
  { name: "Marysville", state: "Washington" },
  { name: "Lakewood", state: "Washington" },
  { name: "Redmond", state: "Washington" },
  { name: "Shoreline", state: "Washington" },
  { name: "Richland", state: "Washington" },
  { name: "Sammamish", state: "Washington" },
  { name: "Burien", state: "Washington" },
  { name: "Olympia", state: "Washington" },
  { name: "Lacey", state: "Washington" },
  { name: "Edmonds", state: "Washington" },
  { name: "Bremerton", state: "Washington" },
  { name: "Puyallup", state: "Washington" },
  { name: "Lynnwood", state: "Washington" },
  { name: "Bothell", state: "Washington" },

  // WEST VIRGINIA
  { name: "Charleston", state: "West Virginia" },
  { name: "Huntington", state: "West Virginia" },
  { name: "Morgantown", state: "West Virginia" },
  { name: "Parkersburg", state: "West Virginia" },
  { name: "Wheeling", state: "West Virginia" },
  { name: "Weirton", state: "West Virginia" },
  { name: "Fairmont", state: "West Virginia" },
  { name: "Martinsburg", state: "West Virginia" },
  { name: "Beckley", state: "West Virginia" },
  { name: "Clarksburg", state: "West Virginia" },
  { name: "South Charleston", state: "West Virginia" },
  { name: "Teays Valley", state: "West Virginia" },
  { name: "St. Albans", state: "West Virginia" },
  { name: "Vienna", state: "West Virginia" },
  { name: "Bluefield", state: "West Virginia" },

  // WISCONSIN
  { name: "Milwaukee", state: "Wisconsin" },
  { name: "Madison", state: "Wisconsin" },
  { name: "Green Bay", state: "Wisconsin" },
  { name: "Kenosha", state: "Wisconsin" },
  { name: "Racine", state: "Wisconsin" },
  { name: "Appleton", state: "Wisconsin" },
  { name: "Waukesha", state: "Wisconsin" },
  { name: "Eau Claire", state: "Wisconsin" },
  { name: "Oshkosh", state: "Wisconsin" },
  { name: "Janesville", state: "Wisconsin" },
  { name: "West Allis", state: "Wisconsin" },
  { name: "La Crosse", state: "Wisconsin" },
  { name: "Sheboygan", state: "Wisconsin" },
  { name: "Wauwatosa", state: "Wisconsin" },
  { name: "Fond du Lac", state: "Wisconsin" },
  { name: "New Berlin", state: "Wisconsin" },
  { name: "Wausau", state: "Wisconsin" },
  { name: "Brookfield", state: "Wisconsin" },
  { name: "Greenfield", state: "Wisconsin" },
  { name: "Beloit", state: "Wisconsin" },
  { name: "Manitowoc", state: "Wisconsin" },
  { name: "West Bend", state: "Wisconsin" },
  { name: "Sun Prairie", state: "Wisconsin" },
  { name: "Superior", state: "Wisconsin" },
  { name: "Stevens Point", state: "Wisconsin" },

  // WYOMING
  { name: "Cheyenne", state: "Wyoming" },
  { name: "Casper", state: "Wyoming" },
  { name: "Laramie", state: "Wyoming" },
  { name: "Gillette", state: "Wyoming" },
  { name: "Rock Springs", state: "Wyoming" },
  { name: "Sheridan", state: "Wyoming" },
  { name: "Green River", state: "Wyoming" },
  { name: "Evanston", state: "Wyoming" },
  { name: "Riverton", state: "Wyoming" },
  { name: "Jackson", state: "Wyoming" },
  { name: "Cody", state: "Wyoming" },
  { name: "Rawlins", state: "Wyoming" },
  { name: "Lander", state: "Wyoming" },
  { name: "Torrington", state: "Wyoming" },
  { name: "Douglas", state: "Wyoming" }
];

export default US_CITIES;
